AllCops:
  TargetRubyVersion: 2.4.2

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '*.gemspec'
    - '**/*.rake'
    - 'spec/**/*.rb'

Metrics/MethodLength:
  Exclude:
    - 'spec/**/*.rb'

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120
